version: '3'
services:
  client:
    container_name: advanced-react-patterns
    build: .
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/web
    command: /bin/bash -c "npm i && npm start"
